### ISSUE TITLE
提供一个本地编译hera系统，构建镜像的文档

### ISSUE THREAD

**Issue by keisni** [XiaoMi/mone#104]
1.注明开发环境，如需要的jdk版本、maven版本、gradle版本等。（也可以提供一个开发环境的docker镜像）
2.从编译到构建docker镜像的可执行步骤。（可以考虑通过Makefile维护）

**Comment by goodjava** [comment]
目前已经提供operator 了.可以用那个部署到k8s.支持一键部署

**Comment by shanwb** [comment]
https://github.com/XiaoMi/mone/blob/master/hera-all/README.md
