### ISSUE TITLE
依赖项dubbo无法获取

### ISSUE THREAD

**Issue by keisni** [XiaoMi/mone#105]
[ERROR] Failed to execute goal on project log: Could not resolve dependencies for project run.mone:log:jar:1.7-SNAPSHOT: Could not find artifact org.apache.dubbo:dubbo:jar:2.7.0-youpin-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :log

**Comment by goodjava** [comment]
今天给你解下

**Comment by goodjava** [comment]
需要修改下maven 的配置
引入maven中央仓库
拉包不需要申请任何权限，只需要修改maven的settings.xml，添加ossrh源
<repository>
    <snapshots />
    <id>ossrh</id>
    <name>ossrh-snapshot</name>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
</repository>

如何你的settings.xml里有镜像相关，添加 !ossrh
<mirrors>
    <mirror>
        <id>others</id>
        <mirrorOf>*,!central,!miremote,!snapshots,!ossrh</mirrorOf>
        <url>https://xxxxxtest.text</url>
    </mirror>
</mirrors>

**Comment by goodjava** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/869986/224215391-ca3c8742-c762-4d83-9ef7-d399a6d0220a.png">

**Comment by keisni** [comment]
fixed!

**Comment by xucw** [comment]
@goodjava @keisni 能否给出一份完整的maven仓库配置？本地编译很多包无法下载
