### ISSUE TITLE
hera-operator的镜像无法拉取

### ISSUE THREAD

**Issue by keisni** [XiaoMi/mone#107]
这些应该是私有仓库的镜像
prod-mione-opensource-registry.cn-beijing.cr.aliyuncs.com/prod-mione-opensource/prod-mione-opensource:hera-operator-v5.1
prod-mione-opensource-registry.cn-beijing.cr.aliyuncs.com/prod-mione-opensource/prod-mione-opensource:hera-operator-fe-v1.6

**Comment by shanwb** [comment]
镜像已推至docker hub，拉下代码，重新试试

**Comment by keisni** [comment]
fixed
