### ISSUE TITLE
 jcommon中prometheus包可能会触发空指针问题

### ISSUE THREAD

**Issue by zxlzxl666zxl** [XiaoMi/mone#153]
public Counter getCounter(String metricName, String... labelName) {
      if (constLabels.size() != Prometheus.CONST_LABELS_NUM) {
         return null;
      }
如上面代码，getCounter可能返回null
public PrometheusCounter(Counter cb, String[] lns, String[] lvs) {
        this.myCounter = cb;
        this.labelNames = lns;
        this.labelValues = lvs;
    }
造成myCounter为null，打不了点

**Comment by wodiwudi** [comment]
我们排查下

**Comment by wodiwudi** [comment]
https://github.com/XiaoMi/mone/pull/160 已经修复
