### ISSUE TITLE
根据traceid查看异常

### ISSUE THREAD

**Issue by wenzhhao** [XiaoMi/mone#154]
1、在日志服务里，点击查看链路的超链接，打开的地址不是我们服务器的地址，而是：http://hera.be.mi.com/project-hera-tracing/traceid/0583fee53f9f47e6b750440eca0619be?startTime=1679958832861&endTime=1679987632861
2、链路追踪根据traceid查询，查不到数据。

**Comment by wtt40122** [comment]
已经解决
