### ISSUE TITLE
grafana重启后，所有图表没有了，监控看不到了。

### ISSUE THREAD

**Issue by wenzhhao** [XiaoMi/mone#168]
grafana重启后，所有图表没有了，监控都看不了，是哪里配置有问题，还是bug?

**Comment by wodiwudi** [comment]
之前grafana用到的sqlite本地数据库的存储路径没有挂到PV和PVC，在https://github.com/XiaoMi/mone/pull/160 里已经修复 ，需要重新 kubectl apply 一下 hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/grafana/hera_grafana.yaml 这个文件
