### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by cckmit** [XiaoMi/mone#24]
如何安装

**Comment by shanwb** [comment]
近期我们会提供一个mone-operator 来支持一键安装部署

**Comment by cf1998** [comment]
一键部署operator预计什么时候开发完成

**Comment by haipersist** [comment]
说好的近期提供的一件安装部署呢？或者Get Started。这个项目开源的不完整啊。

**Comment by shanwb** [comment]
hera operator 已提供：https://github.com/XiaoMi/mone/tree/master/hera-all/hera-operator

**Comment by shanwb** [comment]
时间及人力原因，今年主推hera平台开源，mone operator暂不提供

**Comment by cckmit** [comment]
已经删除 这么在xiaomi mone这个项目里面说到dcwlt

**Comment by wangxun520** [comment]
还没完全删除啊？能加下QQ联系吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMi/mone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMi/mone] 如何安装 (Issue #24)





 
已经删除 这么在xiaomi mone这个项目里面说到dcwlt

**Comment by wangxun520** [comment]
![图片](https://github.com/XiaoMi/mone/assets/150280212/0b34b758-de2a-43dc-9f22-be8f95f9e9db)


> 已经删除 这么在xiaomi mone这个项目里面说到dcwlt

还未完全删除，能否完全删除或者加下QQ276760631或者微信wangxun_520联系下，急急急
<img width="898" alt="微信图片_20231110225513" src="https://github.com/XiaoMi/mone/assets/150280212/586d8f8d-38ca-44f7-91ae-5ff924b70b85">

**Comment by cckmit** [comment]
现在在看看 删除了吧 账号比较多
------------------------------------------------------------------
发件人：wangxun520 ***@***.***>
发送时间：2023年11月10日(星期五) 22:51
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [XiaoMi/mone] 如何安装 (Issue #24)
 还没完全删除啊？能加下QQ联系吗？ 
 ------------------&nbsp;原始邮件&nbsp;------------------ 
 发件人: "XiaoMi/mone" ***@***.***&gt;; 
 发送时间:&nbsp;2023年11月10日(星期五) 晚上10:48 
 ***@***.***&gt;; 
 ***@***.******@***.***&gt;; 
 主题:&nbsp;Re: [XiaoMi/mone] 如何安装 (Issue #24) 
 已经删除 这么在xiaomi mone这个项目里面说到dcwlt

**Comment by cckmit** [comment]
删除了 再查询下
------------------------------------------------------------------
发件人：wangxun520 ***@***.***>
发送时间：2023年11月10日(星期五) 22:51
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [XiaoMi/mone] 如何安装 (Issue #24)
 还没完全删除啊？能加下QQ联系吗？ 
 ------------------&nbsp;原始邮件&nbsp;------------------ 
 发件人: "XiaoMi/mone" ***@***.***&gt;; 
 发送时间:&nbsp;2023年11月10日(星期五) 晚上10:48 
 ***@***.***&gt;; 
 ***@***.******@***.***&gt;; 
 主题:&nbsp;Re: [XiaoMi/mone] 如何安装 (Issue #24) 
 已经删除 这么在xiaomi mone这个项目里面说到dcwlt

**Comment by wangxun520** [comment]
还有个     suevip1的号是不是也是你的？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMi/mone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMi/mone] 如何安装 (Issue #24)





 删除了 再查询下
 ------------------------------------------------------------------
 发件人：wangxun520 ***@***.***&gt;
 发送时间：2023年11月10日(星期五) 22:51
 ***@***.***&gt;
 ***@***.***&gt;; ***@***.***&gt;
 主　题：Re: [XiaoMi/mone] 如何安装 (Issue #24)
  还没完全删除啊？能加下QQ联系吗？ 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
  发件人: "XiaoMi/mone" ***@***.***&amp;gt;; 
  发送时间:&amp;nbsp;2023年11月10日(星期五) 晚上10:48 
  ***@***.***&amp;gt;; 
  ***@***.******@***.***&amp;gt;; 
  主题:&amp;nbsp;Re: [XiaoMi/mone] 如何安装 (Issue #24) 
  已经删除 这么在xiaomi mone这个项目里面说到dcwlt

**Comment by cckmit** [comment]
都删除了 剩下的不是我的了

**Comment by wangxun520427** [comment]
> 已经删除 这么在xiaomi mone这个项目里面说到dcwlt

麻烦删除下这条评论，非常感谢！！
