### ISSUE TITLE
请问能够自动化抓包生成关联依赖的上一个接口返回的json字段路径以及参数变量，并且能够自动生成关联参数变量传入到下一个接口，全部自动化实现，无效手动关联可以吗？

### ISSUE THREAD

**Issue by cfy3133** [XiaoMi/mone#315]
![image](https://user-images.githubusercontent.com/43978367/232940882-ae2d3d73-dcd8-40e5-937a-cc7b3a2c3cd5.png)

**Comment by sadadw1** [comment]
请问你这个是接口mock的时候需要的功能，还是正常业务逻辑里就需要？？这种需求很少见

**Comment by cfy3133** [comment]
正常业务，因为srm系统参数太多了，上万行甚至更多都有，开发需求文档有时候又难以及时更新，做接口测试参数依赖非常难做。其实有个开源平台做出来了，但是不是很精确，而且易用性不是很好，所以问下您这个平台是否能做，谢谢！
以下是开源平台做的
![image](https://user-images.githubusercontent.com/43978367/233516406-01239e02-e953-4548-a9b2-9ecc7788b370.png)
