### ISSUE TITLE
hera平台的架构可以分享一下吗

### ISSUE THREAD

**Issue by 876745833** [XiaoMi/mone#44]
hera平台的使用的架构和组件可以分享一下吗

**Comment by shanwb** [comment]
可以的，代码这周会推上来，同步的还会有一个外部演示demo网站

**Comment by shanwb** [comment]
![image](https://user-images.githubusercontent.com/10281341/228166765-6d1c4aaf-f3c4-4dd3-b350-ede08ebacf88.png)
