### ISSUE TITLE
有没有微信群

### ISSUE THREAD

**Issue by yang724687930** [XiaoMi/mone#501]
想了解一下mone或者天穹的微信群

**Comment by sadadw1** [comment]
可以先关注一下Mone的微信公众号：天穹云原生。上面有一些已发表的文章可以帮助你快速、深入地了解Mone中的产品

**Comment by sadadw1** [comment]
![1e299c094b19a44a5f556e9d92713bc](https://github.com/XiaoMi/mone/assets/128116675/47830882-471c-4318-96a7-d8392eeb9bda)
这是微信群二维码，只有七天有效期，请尽快加入哈

**Comment by yang724687930** [comment]
您重新发一下

**Comment by JasirVoriya** [comment]
同求微信群，麻烦可以重新发一下嘛，前辈
