### ISSUE TITLE
求新手教程

### ISSUE THREAD

**Issue by flashpig** [XiaoMi/mone#531]
跪求新手教程，能本地部署的简单教程

**Comment by sadadw1** [comment]
如果是要部署Hera，可以在参考Hera部署文档：
https://github.com/XiaoMi/mone/blob/master/hera-all/readme/deploy/hera-deploy-document.md

**Comment by ChangJinLong** [comment]
> 如果是要部署Hera，可以在参考Hera部署文档： https://github.com/XiaoMi/mone/blob/master/hera-all/readme/deploy/hera-deploy-document.md

这里也包含 miline 流水线吗？
