### ISSUE TITLE
项目 clone 出现错误

### ISSUE THREAD

**Issue by FangPengbo** [XiaoMi/mone#74]
`git clone https://github.com/XiaoMi/mone `
 
 Error downloading common/test/src/main/java/com/xiaomi/youpin/test/codefilter/c/test-1.4-SNAPSHOT.jarf9df4eae49d52c33425d54fd635lee7d7928fa91f37c87189408f44411348ffc):batch response: This repository is over its data quota.Account responsible for LFS bandwidth should purchase more data packs to restore access. 

@rikaaa0928

**Comment by wtt40122** [comment]
git lfs install --skip-smudge,please before clone execute this command
