### ISSUE TITLE
[Request] Linux Kernel Source For Redmi Note 11 (Spes)

### ISSUE THREAD

**Issue by imannig** [XiaoMi/mone#91]
Hey 
@Xiaomi
, we appreciate your commitment to providing great products. But when it comes to respecting the GPL license, we want to make sure you're doing the right thing. Please release the modified Android kernel source code so that everyone can benefit from it! #RespectGPL

**Comment by caochengxiang** [comment]
Please contact Redmi colleagues to deal with it. We are not responsible for the content of Android phones.
